solution task2
Organization2374/Task-2 pull request #1
Opened 2024-08-09 15:59 UTC by Skwotik

2024-08-09 16:32 UTC, pdasilem requested changes
какая это задача? если вторая - то это должен быть хибернейт

2024-08-09 17:04 UTC, Skwotik commented
> какая это задача? если вторая - то это должен быть хибернейт

Это я уже пошел по Спрингу, сами репозитории названы как в оригинале.
С хибером решение буддет в Task1, после вашего апрува JDBC

2024-08-09 17:47 UTC, Skwotik commented
задача 2.1.2

2024-08-14 05:23 UTC, pdasilem approved these changes

2024-08-14 11:33 UTC, merged